services:
  postgres:
    image: postgres:17
    container_name: scentvault-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: scentvault

    ports:
      - "5433:5432"

    volumes:
      - scentvault_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: scentvault-mongo
    restart: unless-stopped
    
    ports:
      - "27017:27017"
    
    volumes:
      - mongo_data:/data/db
    
    command: mongod --noauth

volumes:
  scentvault_data:
  mongo_data:
